# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_Pid_Motor_Ctrl_0_1/EES_335_Pid_Motor_Ctrl_0_1.xci
# IP: The module: 'EES_335_Pid_Motor_Ctrl_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_Pid_Motor_Ctrl_0_1/src/PID_CONTOR_0_1/PID_CONTOR_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PID_CONTOR_0 || ORIG_REF_NAME==PID_CONTOR_0} -quiet] -quiet

# XDC: e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_Pid_Motor_Ctrl_0_1/src/PID_CONTOR_0_1/constraints/PID_CONTOR_ooc.xdc

# IP: e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_Pid_Motor_Ctrl_0_1/EES_335_Pid_Motor_Ctrl_0_1.xci
# IP: The module: 'EES_335_Pid_Motor_Ctrl_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_Pid_Motor_Ctrl_0_1/src/PID_CONTOR_0_1/PID_CONTOR_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PID_CONTOR_0 || ORIG_REF_NAME==PID_CONTOR_0} -quiet] -quiet

# XDC: e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_Pid_Motor_Ctrl_0_1/src/PID_CONTOR_0_1/constraints/PID_CONTOR_ooc.xdc
