set_property IOSTANDARD LVCMOS33 [get_ports {I2C_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {I2C_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rst[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_1_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_1_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_txd]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux13_v_n]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux13_v_p]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports vga_hsync]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports vga_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports href]
set_property IOSTANDARD LVCMOS33 [get_ports L_A]
set_property IOSTANDARD LVCMOS33 [get_ports L_B]
set_property IOSTANDARD LVCMOS33 [get_ports L_N]
set_property IOSTANDARD LVCMOS33 [get_ports L_P]
set_property IOSTANDARD LVCMOS33 [get_ports R_A]
set_property IOSTANDARD LVCMOS33 [get_ports R_B]
set_property IOSTANDARD LVCMOS33 [get_ports R_P]
set_property IOSTANDARD LVCMOS33 [get_ports R_N]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]
set_property IOSTANDARD LVCMOS33 [get_ports {pwd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports pclk]
set_property IOSTANDARD LVCMOS33 [get_ports xclk]


set_property PACKAGE_PIN W13 [get_ports {sw_tri_i[3]}]
set_property PACKAGE_PIN V12 [get_ports {sw_tri_i[2]}]
set_property PACKAGE_PIN V13 [get_ports {sw_tri_i[1]}]
set_property PACKAGE_PIN U13 [get_ports {sw_tri_i[0]}]
set_property PACKAGE_PIN W16 [get_ports {led_tri_o[7]}]
set_property PACKAGE_PIN V16 [get_ports {led_tri_o[6]}]
set_property PACKAGE_PIN U15 [get_ports {led_tri_o[5]}]
set_property PACKAGE_PIN U14 [get_ports {led_tri_o[4]}]
set_property PACKAGE_PIN W15 [get_ports {led_tri_o[3]}]
set_property PACKAGE_PIN U17 [get_ports {led_tri_o[2]}]
set_property PACKAGE_PIN Y14 [get_ports {led_tri_o[1]}]
set_property PACKAGE_PIN W14 [get_ports {led_tri_o[0]}]
set_property PACKAGE_PIN U20 [get_ports {left_tri_o[1]}]
set_property PACKAGE_PIN T20 [get_ports {left_tri_o[0]}]
set_property PACKAGE_PIN P20 [get_ports {right_tri_o[1]}]
set_property PACKAGE_PIN N20 [get_ports {right_tri_o[0]}]
set_property PACKAGE_PIN K19 [get_ports {rst[0]}]
set_property PACKAGE_PIN J19 [get_ports {pwd[0]}]
set_property PACKAGE_PIN L19 [get_ports pclk]
set_property PACKAGE_PIN M19 [get_ports {I2C_tri_io[1]}]
set_property PACKAGE_PIN M20 [get_ports {I2C_tri_io[0]}]
set_property PACKAGE_PIN D20 [get_ports {data_in[7]}]
set_property PACKAGE_PIN D19 [get_ports {data_in[6]}]
set_property PACKAGE_PIN K17 [get_ports {data_in[3]}]
set_property PACKAGE_PIN C20 [get_ports {data_in[1]}]

set_property PACKAGE_PIN V17 [get_ports L_A]
set_property PACKAGE_PIN V18 [get_ports L_B]
set_property PACKAGE_PIN W18 [get_ports R_A]
set_property PACKAGE_PIN W19 [get_ports R_B]
set_property PACKAGE_PIN R17 [get_ports L_N]
set_property PACKAGE_PIN R16 [get_ports L_P]
set_property PACKAGE_PIN R18 [get_ports R_N]
set_property PACKAGE_PIN T17 [get_ports R_P]
set_property PACKAGE_PIN Y17 [get_ports uart_rtl_1_rxd]
set_property PACKAGE_PIN Y16 [get_ports uart_rtl_1_txd]
set_property PACKAGE_PIN V20 [get_ports uart_rtl_0_rxd]
set_property PACKAGE_PIN W20 [get_ports uart_rtl_0_txd]
set_property PACKAGE_PIN V20 [get_ports uart_rtl_rxd]
set_property PACKAGE_PIN W20 [get_ports uart_rtl_txd]

set_property IOSTANDARD LVCMOS33 [get_ports {led_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_tri_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_tri_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_tri_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_tri_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {left_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {left_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {right_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {right_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_tri_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_tri_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_tri_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_tri_i[3]}]
set_property PACKAGE_PIN G20 [get_ports Vaux13_v_n]



set_property PACKAGE_PIN L14 [get_ports {vga_blue[3]}]
set_property PACKAGE_PIN L15 [get_ports {vga_blue[2]}]
set_property PACKAGE_PIN N15 [get_ports {vga_blue[1]}]
set_property PACKAGE_PIN N16 [get_ports {vga_blue[0]}]

set_property PACKAGE_PIN M15 [get_ports {vga_green[3]}]
set_property PACKAGE_PIN M14 [get_ports {vga_green[2]}]
set_property PACKAGE_PIN J16 [get_ports {vga_green[1]}]
set_property PACKAGE_PIN K16 [get_ports {vga_green[0]}]

set_property PACKAGE_PIN F20 [get_ports {vga_red[3]}]
set_property PACKAGE_PIN F19 [get_ports {vga_red[2]}]
set_property PACKAGE_PIN H18 [get_ports {vga_red[1]}]
set_property PACKAGE_PIN J18 [get_ports {vga_red[0]}]

set_property PACKAGE_PIN F16 [get_ports vga_hsync]
set_property PACKAGE_PIN F17 [get_ports vga_vsync]



set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets pclk_IBUF]



set_property IOSTANDARD LVCMOS33 [get_ports {I2C_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {I2C_tri_o[1]}]

set_property PACKAGE_PIN L20 [get_ports vsync]
set_property PACKAGE_PIN E17 [get_ports href]
set_property PACKAGE_PIN B19 [get_ports {data_in[4]}]
set_property PACKAGE_PIN H16 [get_ports {data_in[2]}]
set_property PACKAGE_PIN A20 [get_ports {data_in[0]}]
set_property PACKAGE_PIN D18 [get_ports xclk]
set_property PACKAGE_PIN B20 [get_ports {data_in[5]}]


set_property PACKAGE_PIN P16 [get_ports RFID_rxd]
set_property PACKAGE_PIN P15 [get_ports RFID_txd]
set_property IOSTANDARD LVCMOS33 [get_ports RFID_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports RFID_txd]

set_property IOSTANDARD LVCMOS33 [get_ports IIC_1_0_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_1_0_sda_io]
set_property PACKAGE_PIN H17 [get_ports {I2C_tri_o[1]}]
set_property PACKAGE_PIN H15 [get_ports {I2C_tri_o[0]}]
set_property PACKAGE_PIN M19 [get_ports IIC_1_0_scl_io]
set_property PACKAGE_PIN M20 [get_ports IIC_1_0_sda_io]
