# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/EES335.xdc

# Block Designs: bd/EES_335/EES_335.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_335 || ORIG_REF_NAME==EES_335} -quiet] -quiet

# IP: bd/EES_335/ip/EES_335_processing_system7_0_0/EES_335_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_335_processing_system7_0_0 || ORIG_REF_NAME==EES_335_processing_system7_0_0} -quiet] -quiet

# IP: bd/EES_335/ip/EES_335_rst_ps7_0_100M_0/EES_335_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_335_rst_ps7_0_100M_0 || ORIG_REF_NAME==EES_335_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/EES_335/ip/EES_335_Pid_Motor_Ctrl_0_0/EES_335_Pid_Motor_Ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_335_Pid_Motor_Ctrl_0_0 || ORIG_REF_NAME==EES_335_Pid_Motor_Ctrl_0_0} -quiet] -quiet

# IP: bd/EES_335/ip/EES_335_Pid_Motor_Ctrl_0_1/EES_335_Pid_Motor_Ctrl_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_335_Pid_Motor_Ctrl_0_1 || ORIG_REF_NAME==EES_335_Pid_Motor_Ctrl_0_1} -quiet] -quiet

# IP: bd/EES_335/ip/EES_335_ps7_0_axi_periph_1/EES_335_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_335_ps7_0_axi_periph_1 || ORIG_REF_NAME==EES_335_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/EES_335/ip/EES_335_xbar_1/EES_335_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_335_xbar_1 || ORIG_REF_NAME==EES_335_xbar_1} -quiet] -quiet

# IP: bd/EES_335/ip/EES_335_OV_Sensor_ML_0_0/EES_335_OV_Sensor_ML_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_335_OV_Sensor_ML_0_0 || ORIG_REF_NAME==EES_335_OV_Sensor_ML_0_0} -quiet] -quiet

# IP: bd/EES_335/ip/EES_335_axi_vdma_0_0/EES_335_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_335_axi_vdma_0_0 || ORIG_REF_NAME==EES_335_axi_vdma_0_0} -quiet] -quiet

# IP: bd/EES_335/ip/EES_335_v_axi4s_vid_out_0_0/EES_335_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_335_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==EES_335_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/EES_335/ip/EES_335_v_tc_0_0/EES_335_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_335_v_tc_0_0 || ORIG_REF_NAME==EES_335_v_tc_0_0} -quiet] -quiet

# IP: bd/EES_335/ip/EES_335_v_vid_in_axi4s_0_0/EES_335_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_335_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==EES_335_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: bd/EES_335/ip/EES_335_xlslice_0_0/EES_335_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_335_xlslice_0_0 || ORIG_REF_NAME==EES_335_xlslice_0_0} -quiet] -quiet

# IP: bd/EES_335/ip/EES_335_xlslice_0_1/EES_335_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_335_xlslice_0_1 || ORIG_REF_NAME==EES_335_xlslice_0_1} -quiet] -quiet

# IP: bd/EES_335/ip/EES_335_xlslice_0_2/EES_335_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_335_xlslice_0_2 || ORIG_REF_NAME==EES_335_xlslice_0_2} -quiet] -quiet

# IP: bd/EES_335/ip/EES_335_axi_smc_0/EES_335_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_335_axi_smc_0 || ORIG_REF_NAME==EES_335_axi_smc_0} -quiet] -quiet

# IP: bd/EES_335/ip/EES_335_hls_sobel_0_1/EES_335_hls_sobel_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_335_hls_sobel_0_1 || ORIG_REF_NAME==EES_335_hls_sobel_0_1} -quiet] -quiet

# IP: bd/EES_335/ip/EES_335_xlconstant_0_0/EES_335_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_335_xlconstant_0_0 || ORIG_REF_NAME==EES_335_xlconstant_0_0} -quiet] -quiet

# IP: bd/EES_335/ip/EES_335_xlconstant_0_1/EES_335_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_335_xlconstant_0_1 || ORIG_REF_NAME==EES_335_xlconstant_0_1} -quiet] -quiet

# IP: bd/EES_335/ip/EES_335_xlconcat_0_0/EES_335_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_335_xlconcat_0_0 || ORIG_REF_NAME==EES_335_xlconcat_0_0} -quiet] -quiet

# IP: bd/EES_335/ip/EES_335_axi_gpio_0_0/EES_335_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_335_axi_gpio_0_0 || ORIG_REF_NAME==EES_335_axi_gpio_0_0} -quiet] -quiet

# IP: bd/EES_335/ip/EES_335_axi_uartlite_0_0/EES_335_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_335_axi_uartlite_0_0 || ORIG_REF_NAME==EES_335_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/EES_335/ip/EES_335_axi_uartlite_1_0/EES_335_axi_uartlite_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_335_axi_uartlite_1_0 || ORIG_REF_NAME==EES_335_axi_uartlite_1_0} -quiet] -quiet

# IP: bd/EES_335/ip/EES_335_auto_pc_0/EES_335_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_335_auto_pc_0 || ORIG_REF_NAME==EES_335_auto_pc_0} -quiet] -quiet

# XDC: bd/EES_335/EES_335_ooc.xdc
