# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/EES_Board/EES_335/EES_335.cache/wt [current_project]
set_property parent.project_path E:/EES_Board/EES_335/EES_335.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  e:/EES_Board/EES_335/OV_Sensor_ML
  e:/EES_Board/EES_335/hls_opecv_hls_hls_sobel_1_2
  e:/EES_Board/EES_335/ip_repo/EES_SmarterCar_Motor_Ctrl_1.1
} [current_project]
set_property ip_output_repo e:/EES_Board/EES_335/EES_335.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib E:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/hdl/EES_335_wrapper.v
add_files E:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/EES_335.bd
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_processing_system7_0_0/EES_335_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_rst_ps7_0_100M_0/EES_335_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_rst_ps7_0_100M_0/EES_335_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_rst_ps7_0_100M_0/EES_335_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_Pid_Motor_Ctrl_0_0/src/PID_CONTOR_0_1/constraints/PID_CONTOR_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_Pid_Motor_Ctrl_0_1/src/PID_CONTOR_0_1/constraints/PID_CONTOR_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_xbar_1/EES_335_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_axi_vdma_0_0/EES_335_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_axi_vdma_0_0/EES_335_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_axi_vdma_0_0/EES_335_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_v_axi4s_vid_out_0_0/EES_335_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_v_axi4s_vid_out_0_0/EES_335_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_v_tc_0_0/EES_335_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_v_tc_0_0/EES_335_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_v_vid_in_axi4s_0_0/EES_335_v_vid_in_axi4s_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_v_vid_in_axi4s_0_0/EES_335_v_vid_in_axi4s_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_axi_smc_0/bd_0/ip/ip_10/bd_aac7_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_axi_smc_0/bd_0/ip/ip_16/bd_aac7_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_axi_smc_0/bd_0/ip/ip_20/bd_aac7_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_axi_smc_0/bd_0/ip/ip_21/bd_aac7_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_axi_smc_0/bd_0/ip/ip_22/bd_aac7_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_axi_smc_0/bd_0/ip/ip_23/bd_aac7_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_axi_smc_0/bd_0/ip/ip_24/bd_aac7_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_axi_smc_0/bd_0/ip/ip_25/bd_aac7_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_axi_smc_0/bd_0/ip/ip_17/bd_aac7_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_axi_smc_0/bd_0/ip/ip_18/bd_aac7_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_axi_smc_0/bd_0/ip/ip_19/bd_aac7_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_axi_smc_0/bd_0/ip/ip_11/bd_aac7_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_axi_smc_0/bd_0/ip/ip_12/bd_aac7_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_axi_smc_0/bd_0/ip/ip_2/bd_aac7_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_axi_smc_0/bd_0/ip/ip_3/bd_aac7_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_axi_smc_0/bd_0/ip/ip_4/bd_aac7_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_axi_smc_0/bd_0/ip/ip_5/bd_aac7_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_axi_smc_0/bd_0/ip/ip_6/bd_aac7_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_axi_smc_0/bd_0/ip/ip_1/bd_aac7_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_axi_smc_0/bd_0/ip/ip_1/bd_aac7_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_hls_sobel_0_1/constraints/hls_sobel_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_axi_gpio_0_0/EES_335_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_axi_gpio_0_0/EES_335_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_axi_gpio_0_0/EES_335_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_axi_uartlite_0_0/EES_335_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_axi_uartlite_0_0/EES_335_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_axi_uartlite_0_0/EES_335_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_axi_uartlite_1_0/EES_335_axi_uartlite_1_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_axi_uartlite_1_0/EES_335_axi_uartlite_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_axi_uartlite_1_0/EES_335_axi_uartlite_1_0.xdc]
set_property used_in_implementation false [get_files -all e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_auto_pc_0/EES_335_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/EES_335_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/EES_Board/EES_335/EES_335.srcs/constrs_1/new/EES335.xdc
set_property used_in_implementation false [get_files E:/EES_Board/EES_335/EES_335.srcs/constrs_1/new/EES335.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top EES_335_wrapper -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef EES_335_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file EES_335_wrapper_utilization_synth.rpt -pb EES_335_wrapper_utilization_synth.pb"
