# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_xbar_1/EES_335_xbar_1.xci
# IP: The module: 'EES_335_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_xbar_1/EES_335_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'EES_335_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_xbar_1/EES_335_xbar_1.xci
# IP: The module: 'EES_335_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/EES_Board/EES_335/EES_335.srcs/sources_1/bd/EES_335/ip/EES_335_xbar_1/EES_335_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'EES_335_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
